image:
  url: ghcr.io/samerx/wireguard:main
  pullPolicy: Always

wireguard:
  serverAddress: 10.34.0.1/24
  serverCidr: 10.34.0.0/24 # -- Subnet for your VPN, take care not to clash with cluster POD cidr
  natAddSourceNet: true # -- Add the serverCidr to the nat source net option