apiVersion: v1
kind: Service
metadata:
  name: service-wireguard
spec:
  type: NodePort
  selector:
    app: wireguard
  ports:
    - name: port-wg
      protocol: UDP
      port: 9090
      targetPort: 9090
      nodePort: 30909 # You can specify a port or leave it to be dynamically assigned
