apiVersion: v1
kind: Service
metadata:
  name: service-wgrest
  labels:
    app: wireguard
spec:
  type: NodePort
  selector:
    app: wireguard
  ports:
  - name: wgrest
    port: 51800
    targetPort: 51800    
    nodePort: 31800 # You can specify a port or leave it to be dynamically assigned
  
