apiVersion: v1
kind: Service
metadata:
  name: service-wireguard
spec:
  type: NodePort
  selector:
    app: wireguard
  ports:
    - protocol: UDP
      port: 51820
      targetPort: 51820
      nodePort: 31820 # You can specify a port or leave it to be dynamically assigned
