apiVersion: v1
kind: Service
metadata:
  name: service-wgrest
  labels:
    app: wireguard
spec:
  type: NodePort
  selector:
    app: wireguard
  ports:
  - name: wgrest
    port: 8080
    targetPort: 8080    
    nodePort: 30808 # You can specify a port or leave it to be dynamically assigned
  
